service: shared
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage,'dev'}

functions:
  function1:
    handler: index.handler


resources:
  Outputs:
    sharedValueA:
      Value: 'SHARED_VALUE_A'
    sharedValueB:
      Value: 'SHARED_VALUE_B'
