service: service-a
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage,'dev'}
  environment:
    SHARED_VALUE: ${param:sharedValueA}

functions:
  function1:
    handler: index.handler
