name: Deploy sls to BETA
run-name: ${{ github.actor }} is deploying the Project to [BETA] STAGE
on: [push]
permissions: read-all
env:
  stage: beta
  service: service-a service-b

jobs:
  prepare_deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: check out repository code
        uses: actions/checkout@master
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configuration NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check Node Version
        run: node -v
      - name: Cache Node Modules
        id: npm_cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
      - if: ${{ steps.npm_cache.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install Serverless Framework
        run: |
          npm install -g serverless
          npm install -D @serverless/compose
          npm install -D serverless-layers
  deploy_using_sls:
    uses: ./.github/workflows/serverless-deploy.yml
    secrets:
      aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-key: ${{ secrets.AWS_ACCESS_KEY }}
