name: deploy service-a to aws
run-name: ${{ github.actor }} deploying service-a toAWS
on:
  push:
    branches:
      - github_action
    paths:
      - 'service-a/**/*.js'
      - 'service-a/*.json'
      - 'service-a/*.yml'
permissions: read-all

jobs:
  call-deployment-workflow:
    uses: ./.github/workflows/deployment.yml
    with:
      stage: beta
      service: service-a
    secrets: inherit

